# Generated by Django 3.2.6 on 2021-09-14 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dessert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert',
            old_name='desc',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='dessert',
            name='category',
            field=models.CharField(choices=[('Cookies', 'Cookies'), ('Cakes', 'Cakes'), ('Drinks', 'Drinks'), ('Pastry', 'Pastry')], default='Cookies', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dessert',
            name='image_src',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dessert',
            name='steps',
            field=models.CharField(default='test_default', max_length=10000000),
            preserve_default=False,
        ),
    ]
