# Generated by Django 3.2.6 on 2021-09-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dessert', '0002_auto_20210913_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert',
            old_name='name',
            new_name='title',
        ),
    ]
