# Generated by Django 3.2.6 on 2021-09-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dessert', '0003_rename_name_dessert_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert',
            old_name='image_src',
            new_name='img_src',
        ),
    ]
