# Generated by Django 3.2.6 on 2021-11-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessert', '0006_alter_dessert_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='description',
            field=models.CharField(default='test', max_length=10000000),
            preserve_default=False,
        ),
    ]
